### PR TITLE
Implement `parallax_background` example

### LINKED ISSUE #16: Parallax example
Add an example that shows how to create a parallax effect

### PR DESCRIPTION
**Pull request by avaxar**
This PR would close #16.

### CODE REVIEW

**Comment by avaxar** [comment]
Following from Discord, I do not think that OOP encapsulation is necessary for this. One would just be teaching Java to beginners at this point.

**Review by blankRiot96 — CHANGES_REQUESTED** [review]
Art looks great. Avoid usage of non-constant global variables. `global` shadows the builtin `global` function. 
Change to follow this structure:
```py
class Game:
    SCREEN: pygame.Surface = pygame.display.set_mode(...)
    ...

    def __init__(self):
        self.running = True

    async def run(self):
        while self.running:
            self.loop()
            await asyncio.sleep(0)

    def loop(self):
        ...
```

**Review by pycoinfu — COMMENTED** [review]
what is `background.kra`?
please try to avoid `global` keyword. also, every other example uses OOP, so i think you should use it too

**Comment by avaxar** [comment]
> what is `background.kra`? please try to avoid `global` keyword. also, every other example uses OOP, so i think you should use it too

`background.kra` is the Krita file for the layers of the parallax background assets. I figure to leave it there in case somebody else wants to remaster it. Like in the reply above of mine, I do not think OOP encapsulation is necessary.

**Comment by Matiiss** [comment]
@avaxar rename `globals.py` to `common.py` (and adjust code accordingly)

**Review by Matiiss — APPROVED** [review]
Looks good

**Review by blankRiot96 — APPROVED** [review]

**Pull request merged**
