### PR TITLE
Added __init__.py, more docstrings, fixed some comments

### PR DESCRIPTION
**Pull request by pycoinfu**

### CODE REVIEW

**Comment by blankRiot96** [comment]
Should header files about the MIT license be included in examples?
```py
"""
This file is a part of the 'Pygame Examples (pgex)' source code.
The source code is distributed under the MIT license.
"""
```

**Comment by pycoinfu** [comment]
should i add this to every file of the example, or do i add a new file for this?

**Comment by blankRiot96** [comment]
> @blankRiot96 should i add this at the top of every file of the example, or create a new file for this?

Add at the top of every fiile

**Review by Matiiss — DISMISSED** [review]
Seems good

**Comment by blankRiot96** [comment]
Wait I'll add doc-string headers

**Review by blankRiot96 — APPROVED** [review]
LGTM!

**Review by Matiiss — APPROVED** [review]
Looks good, thanks for headers

**Comment by pycoinfu** [comment]
thanks 💜

**Pull request merged**
