### PR TITLE
Added button

### PR DESCRIPTION
**Pull request by novialriptide**
This code was taken directly from https://github.com/novialriptide/SakuyaEngine

### CODE REVIEW

**Comment by blankRiot96** [comment]
Code looks great

Why a `bg_color` variable?  It would be better to encourage the usage of colour strings that pygame offers - `"black"`

**Comment by novialriptide** [comment]
> Code looks great
> 
> Why is `bg_color` global?

It's so that `bg_color` would be modified outside of the method.

**Review by Matiiss — CHANGES_REQUESTED** [review]
Seems that you can easily change
```py
surface.blit(
    self.text_surf,
    pygame.Vector2(self.rect.center)
    - pygame.Vector2(self.text_surf.get_size()) / 2,
)
```
to simply
```py
 surface.blit(self.text_surf, self.rect)
```

Another thing is that `method` probably should have a default value of `lambda: None`:
```py
def __init__(self, x, y, width, height, text, text_color, bg_color, method=lambda: None):
```
otherwise not passing callback will raise an error along the lines of `NoneType not callable`.

One minor thing could be to instead of asking for `x`, `y`, `width` and `height` as separate arguments they could be merged in `pos` and `size`:
```py
def __init__(self, pos, size, text, text_color, bg_color, method=lambda: None):
```

The arguments also lack type annotations.

Lastly something maybe should be done about using that `global` for the background color? Not sure, I guess it can also stay as a `global` for this simple example? Like one way to avoid it could be to use a data dictionary of some sort but that seems unnecessary.

P.S.
Two other minor things: `update` before `draw` and `self.rect.collidepoint(pygame.mouse.get_pos())` and `pygame.mouse.get_pressed()[0]` could be called only once, value assigned to a variable and that used for checks in the `update` method

**Review by Matiiss — APPROVED** [review]
LGTM!

**Pull request merged**
