### PR TITLE
Created issue templates

### PR DESCRIPTION
**Pull request by Matiiss**
Issue templates for helping with making new issues, especially for suggesting examples

### CODE REVIEW

**Comment by Matiiss** [comment]
How to improve the example suggestion template?

**Comment by blankRiot96** [comment]
@Matiiss looks like the standard example template, I dont think it requires improvement!

**Review by blankRiot96 — APPROVED** [review]
LGTM!

**Review by pycoinfu — APPROVED** [review]
lgtm!

**Pull request merged**
